# Generated by Django 5.1.4 on 2026-04-16 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('carrier', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('origin_country', models.CharField(blank=True, max_length=100)),
                ('dest_country', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_transit', 'En transit'), ('out_for_delivery', 'En livraison'), ('delivered', 'Livré'), ('exception', 'Incident'), ('expired', 'Expiré')], default='pending', max_length=30)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracking.parcel')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
