# Generated by Django 5.1.4 on 2026-04-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='flight_number',
            field=models.CharField(blank=True, help_text='Ex: AF447, pour liaison FlightRadar', max_length=20, null=True),
        ),
    ]
