# Generated by Django 5.1.4 on 2026-04-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_parcel_flight_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='last_live_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='last_live_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='last_live_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
