# Generated by Django 5.1.4 on 2026-04-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_parcel_last_live_at_parcel_last_live_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingevent',
            name='flight_iata',
            field=models.CharField(blank=True, help_text='Code IATA du vol extrait (ex: UA123, AF447)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='transport_mode',
            field=models.CharField(blank=True, choices=[('air', 'Aérien'), ('road', 'Terrestre'), ('sea', 'Maritime'), ('unknown', 'Inconnu')], default='unknown', help_text='Mode de transport détecté pour cet événement', max_length=20),
        ),
    ]
