# Generated by Django 5.1.4 on 2026-05-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_trackingevent_flight_iata_transport_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingevent',
            name='estimated_arrival',
            field=models.DateTimeField(blank=True, help_text="Timestamp d'arrivée estimé du segment (= timestamp du prochain event)", null=True),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='estimated_departure',
            field=models.DateTimeField(blank=True, help_text='Timestamp de départ estimé du segment (= timestamp de cet event)', null=True),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='simulated',
            field=models.BooleanField(default=False, help_text='True si le SimulationEngine a calculé ce segment'),
        ),
    ]
